### ISSUE TITLE
Bot doesn't play until restarted

### ISSUE THREAD

**Issue by arbauman** [Geo1088/listen.moe-streaming-bot#20]
I encountered this bug while I was testing but it was doing it even before I made changes.  When the bot joins a VC (using the ~~join command), it doesn't actually start playing in that channel until the bot is restarted.  Is this happening for others?

**Comment by Geo1088** [comment]
...this would actually explain a lot. I'll get in touch with the person who's actually hosting the live version of the bot and check this out.

**Comment by kanadeko** [comment]
We tried replicating this and weren't successful. Even created another server, added the bot and it started playing music right away. So I believe there is indeed a bug that sometimes fucks it up by not playing on join, but doesn't happen every time.

**Comment by arbauman** [comment]
Interesting.  I tried it on three servers, including a brand new one, with both my local version and the official one, and it didn't play on join every time.  Spooky stuff.

**Comment by kanadeko** [comment]
Spooky indeed. We should wait until Halloween is over, maybe there are external forces at play here 👻

**Comment by anonymousthing** [comment]
@arbauman, can you try replicate this again? I've fixed an unrelated bug that may have also fixed this issue.

**Comment by arbauman** [comment]
That appears to have fixed it!

**Comment by anonymousthing** [comment]
MAGIC

**Comment by pituseligmann** [comment]
I said we had to wait until Halloween was over! 👻

**Comment by kanadeko** [comment]
It was the Halloween spook 👻
